[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENABLEGITINFO = "true"
  HUGO_EXTENDED = "true"
  GO_VERSION = "1.22"

[context.production.environment]
  HUGO_ENV = "production"
